name: Deploy Project
on: 
  [push,workflow_dispatch] #event/workflow triggers - https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows

jobs:
  test:
    runs-on: ubuntu-latest #runner - https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
    steps:
      - name: Get code #download code from repo
        uses: actions/checkout@v3 #https://github.com/actions/checkout
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code #download code from repo
        uses: actions/checkout@v3 #https://github.com/actions/checkout
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: |
          npm run build
          echo "Build complete"
      - name: Deploy
        run: echo "Deploying ...."